#!/bin/bash

rest-server $@ &

sleep 2

# Check if the rest-server started successfully
if ! kill -0 $! 2>/dev/null; then
    echo "rest-server process hasn't started. Try to run/debug manualy with: $@."
    sleep 1
    exit 1
fi
